language: generic 
sudo: required
services:
  -docker

before_install:
  - docker build -t senkonrad/fib-project -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true senkonrad/fib-project npm test

after_success:
  - docker build -t senkonrad/multi-client ./client
  - docker build -t senkonrad/multi-nginx ./nginx
  - docker build -t senkonrad/multi-server ./server
  - docker build -t senkonrad/multi-worker ./worker
